- hosts: all
  become: true

  tasks:  
#    - local_action: wait_for port=22 

    - name: update
      apt:
        update_cache: yes

    - name: install
      apt:
        name: nginx
        state: present
